# Generated by Django 6.0.6 on 2026-07-05 15:21

import apps.uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('extrato_bancario', 'Extrato Bancário'), ('contas_receber', 'Contas a Receber')], max_length=32, verbose_name='Tipo de arquivo')),
                ('file', models.FileField(upload_to=apps.uploads.models.upload_to_path, verbose_name='Arquivo')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de processamento'), ('processado', 'Processado'), ('erro', 'Erro no processamento')], default='pendente', max_length=16)),
                ('processing_notes', models.TextField(blank=True, help_text='Preenchido pelo motor de conciliação')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo enviado',
                'verbose_name_plural': 'Arquivos enviados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
