# Generated by Django 6.0.6 on 2026-07-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_issues', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'Problema de importação',
                'verbose_name_plural': 'Problemas de importação',
                'ordering': ['uploaded_file', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Número da linha no arquivo.')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('description_normalized', models.CharField(db_index=True, help_text='Descrição sem acentos, maiúscula e sem espaços duplicados, usada na conciliação.', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Linha original do arquivo, para auditoria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'Transação do extrato',
                'verbose_name_plural': 'Transações do extrato',
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['transaction_date'], name='reconciliat_transac_e125e8_idx'), models.Index(fields=['amount'], name='reconciliat_amount_a77524_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Número da linha no arquivo.')),
                ('client_name', models.CharField(max_length=255)),
                ('client_name_normalized', models.CharField(db_index=True, max_length=255)),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Linha original do arquivo, para auditoria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['due_date'], name='reconciliat_due_dat_f2dc6c_idx'), models.Index(fields=['expected_amount'], name='reconciliat_expecte_febac7_idx'), models.Index(fields=['document_number'], name='reconciliat_documen_6eb4ca_idx')],
            },
        ),
    ]
