# Generated by Django 6.0.6 on 2026-07-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('conciliado', 'Conciliado'), ('divergencia', 'Divergência'), ('nao_encontrado', 'Pagamento não encontrado'), ('possivel_duplicado', 'Possível pagamento duplicado')], db_index=True, max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Índice de confiança da correspondência, de 0 a 100.', max_digits=5)),
                ('amount_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_difference_days', models.IntegerField(blank=True, help_text='Diferença de dias entre a transação e o recebido', null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidates_considered', models.JSONField(blank=True, default=list, help_text='Até 5 melhores transações candidatas consideradas, para auditoria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(blank=True, help_text='Transação encontrada.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='reconciliation.banktransaction')),
                ('receivable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_result', to='reconciliation.receivable')),
            ],
            options={
                'verbose_name': 'Resultado da conciliação',
                'verbose_name_plural': 'Resultados da conciliação',
                'ordering': ['receivable__due_date'],
            },
        ),
    ]
